apiVersion: v1
entries:
  productms:
  - created: 2016-10-06T16:23:20.499814565-06:00
    description: Sample java microservice
    name: productms
    sources:
    - https://nlilaramani.github.io/charts
    urls:
    - https://nlilaramani.github.io/charts/productms-1.0.tgz
    version: 1.0
generated: 2016-10-06T16:23:20.499029981-06:00
